version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mgt
      - POSTGRES_PASSWORD=Ll1FGMU8
      - POSTGRES_DB=mgt
    restart: unless-stopped
volumes:
  data:
