version: "3"

services:
  backend:
    build: ./backend
    restart: on-failure
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mgt
      - POSTGRES_PASSWORD=Ll1FGMU8
      - POSTGRES_DB=mgt
  nginx:
    build: ./frontend
    ports:
      - "9000:80"
    depends_on:
      - backend
